sudo: required
services:
  - docker
before_install:
  - docker build -t tyler/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true tyler/docker-react npm run test
language: node_js 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-666049413917"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY